POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": "5",
  "userId" : "662bacc430e36047a6dbf3d4"
}